sudo: required

services:
  - docker

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - DASH_IMAGE=dashboard
    - DASH_DEPLOYMENT=dashboard-deploy
    - DASH_CONTAINER=dashboard-container
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_script:
  - docker-compose up -d
script:
  - docker-compose exec api yarn test
before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then
      rm -rf $HOME/google-cloud-sdk;
      curl https://sdk.cloud.google.com | bash > /dev/null;
    fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud --quiet components update kubectl
deploy:
  - provider: script
    script: chmod +x deploy/deploy-stag.sh && bash deploy/deploy-stag.sh
    skip_cleanup: true
    on:
      branch: development
notifications:
  email: false
