version: '3'

services:
  api:
    container_name: api-cont
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo:3.2.21
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

